### ISSUE TITLE
Highlight escape characters in a string

### ISSUE THREAD

**Issue by chirsz-ever** [dten/pest-sublime#2]
Thanks for the support for editing pest grammer file on sublime text!
I think it would be a improvement if making escape characters highlighted in a string, like the usual practice in other sublime-syntax:
![image](https://user-images.githubusercontent.com/31474766/68566038-41905080-0490-11ea-9fb7-bdfd90945660.png)
the charactor `\n` is highlighted on Rust syntax mode.
![image](https://user-images.githubusercontent.com/31474766/68566426-473a6600-0491-11ea-902b-6050a1343787.png)
And the pest syntax mode don't do it currently.

**Comment by dten** [comment]
Yea that would be good. It should be quite easy if you want to try.
https://github.com/dten/pest-sublime/blob/master/Pest.sublime-syntax#L55
Handles the `\"` case but doesn't highlight it. Giving it a `scope` of `constant.character.escape.pest` will make it highlight. Also the pattern should match more escape characters and be merged with the match above for escaped slash

**Comment by chirsz-ever** [comment]
I would gladly undertake this task.

**Comment by dten** [comment]
resolved via #3
